apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      type: backend
  replicas: 2
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: backend
    spec:
      containers:
        - name: backend
          image: ddarahakit2024/backend:1.0
      terminationGracePeriodSeconds: 3